sonar.projectKey=arbodex
sonar.projectName=Arbodex
sonar.projectVersion=0.2.0
sonar.sources=src
sonar.sourceEncoding=UTF-8
sonar.language=ts
sonar.exclusions=**/*.test.ts,**/*.test.tsx,**/node_modules/**,**/.next/**
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx
